config/routes.rb
Rails.application.routes.draw do
  resources :friends
  # get 'home/index'
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">

    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>
<br/>
  <div class="field form-group">
     <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>
<br/>
  <div class="field form-group">
      <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>
<br/>
  <div class="field form-group">
      <%= form.text_field :phone, class:"form-control", placeholder:"Phone Number" %>
  </div>
<br/>
  <div class="field form-group">
      <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div>
<br/>
<br/>
  <div>
    <%= form.submit class:"btn btn-secondary btn-sm" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<%
=begin%>
 <div id="<%= dom_id friend %>"> 
<%
=end%>

<div class="p-3 mb-2 bg-secondary bg-opacity-25 rounded" >
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= friend.last_name %>
  </h1>
  <p class="lead">
    <%= friend.email %> |
    <%= friend.phone %> |
    <%= friend.twitter %>
  </p>
  
  <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-secondary btn-sm" %> |
  <%= link_to "Back", friends_path, class:"btn btn-dark btn-sm" %>
<br/><br/>
  <%= button_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
</div>

<%
=begin%>
 </div>ß 
<%
=end%>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back", friends_path , class:"btn btn-dark btn-sm"%>
</div>

app/views/friends/index.html.erb
<%
=begin%>
 <p style="color: green"><%= notice %></p>

<h1>Friend List</h1>

<div id="friends">
  <% @friends.each do |friend| %>
    <%= render friend %>
    <p>
      <%= link_to "Show this friend", friend %>
    </p>
  <% end %>
</div>

<%= link_to "New friend", new_friend_path %>
 
<%
=end%>




  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
        <th> </th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <%
=begin%>
 <% if friend.user == current_user %> 
<%
=end%>
        <tr>
          <%
=begin%>
 <td>
<%= link_to friend.first_name + ' ' + friend.last_name, friend %>


          </td> 
<%
=end%>
          
          <td><%= friend.first_name %></td>
          <td><%= friend.last_name %></td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
          
          
          
          
          <td> <%= link_to "Show", friend, class:"btn btn-outline-secondary btn-sm" %></td>
            <%
=begin%>
 <td><%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>  
<%
=end%>
          <%
=begin%>
 <td> <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-outline-secondary btn-sm" %></td>
          <td><%= link_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td> 
<%
=end%>
 
        </tr>
        <%
=begin%>
 <% end %> 
<%
=end%>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Add New Friend', new_friend_path, class:"btn btn-secondary" %>

app/views/friends/new.html.erb
<h1>Add New friend</h1>
<br/>
<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back", friends_path, class: "btn btn-dark btn-sm" %>
</div>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>


<%= render @friend %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
  <%= link_to 'Friend App', root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       
        <li class="nav-item">
        <%= link_to "About Us", home_about_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
        <%= link_to "Friends", friends_path, class:"nav-link" %>
        </li> 
       
        <li class="nav-item">
        <%= link_to "Add Friend", new_friend_path, class:"nav-link" %>
        </li> 


      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<h1>Hello World</h1>
This is my first Rails Webpage

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <%= render 'home/header' %>
  <div class="container"> 
  <br/>
    <%= yield %>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
  </body>
</html>